#!/usr/bin/env python3
"""
ASERT half-life selection study for BitAIcoin -- expanded per explicit
follow-up instruction (2026-09-23): do not freeze a half-life on the basis of
the earlier permanent-shock-only, deterministic-only, MTP-unaware model.

This version:
  - Uses the bit-exact fixed-point CalculateASERT port (contrib/asert_reference.py),
    validated against BCHN's own real source and the algorithm's defining
    mathematical properties -- not a floating-point behavioral stand-in.
  - Adds temporary surge-then-revert scenarios (not just permanent shocks):
    1x -> {10x,100x,1000x} held for {20,100,500} blocks -> back to 1x, with
    post-surge recovery explicitly measured.
  - Adds repeated on/off "pool-hopping" cycles.
  - Adds a stochastic/Poisson-arrival variant alongside the deterministic
    (expected-value) model, run with multiple seeds.
  - Applies BitAIcoin's real, unmodified consensus timestamp constraints:
    nTime > MTP(prev 11 blocks), nTime <= now + MAX_FUTURE_BLOCK_TIME (7200s).
    The MTP floor is the one that can bind during a fast burst (many blocks
    arriving within an 11-block median window); the future-time ceiling binds
    only to a single miner's own dishonestly-stamped block, not to the
    simulation's honest median-driven clock, so it is enforced but rarely
    the constraint that fires here.
  - Compares half-lives {1h, 6h, 1d, 2d} across all of the above. No half-life
    is selected/frozen by this script or in the milestone doc -- comparison
    only, per explicit instruction.

Known limitation, disclosed rather than hidden: this still runs the fixed-
point ASERT math on wall-clock/height inputs generated by a Python-level
scenario driver, not inside the actual C++ consensus code path -- it studies
the DAA's designed behavior under the given scenarios, not the full node
(mempool/relay/mining-software) dynamics that a real pool-hopping event would
also involve.
"""
import bisect
import random
import statistics
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from asert_reference import calculate_asert  # noqa: E402

IBT = 600  # nPowTargetSpacing, seconds
MAX_FUTURE_BLOCK_TIME = 7200  # seconds, confirmed unmodified in src/chain.h
MEDIAN_TIME_SPAN = 11  # blocks, confirmed unmodified

# BitAIcoin's real powLimit (src/kernel/chainparams.cpp:289), confirmed 228-bit.
POW_LIMIT = int("0000000fffffffffffffffffffffffffffffffffffffffffffffffffffffffff", 16)

HALF_LIVES = {
    "1 hour": 3600,
    "6 hours": 21600,
    "1 day": 86400,
    "2 days": 172800,
}


class ChainSim:
    """
    Drives a sequence of blocks through the exact CalculateASERT function,
    tracking real per-block nBits/target, enforcing the real MTP-floor and
    future-time-ceiling consensus constraints on the timestamps fed in, and
    supporting both a deterministic (expected-value arrival) mode and a
    stochastic (Poisson-arrival) mode.
    """

    def __init__(self, half_life, anchor_target=None):
        self.half_life = half_life
        self.anchor_height = 0
        self.anchor_target = anchor_target if anchor_target is not None else POW_LIMIT
        # anchor's PARENT time = 0 (our time origin); anchor's own time is
        # otherwise unused by CalculateASERT (only the parent's time and the
        # anchor's nBits matter) -- this mirrors the real anchor semantics
        # confirmed from BCHN source: ASERTAnchor{nHeight, nBits, nPrevBlockTime}.
        self.anchor_prev_time = 0
        self.heights = [0]
        self.times = [IBT]  # anchor block's own time, arbitrary but > anchor_prev_time; not used by the formula, only by MTP bookkeeping of subsequent blocks
        self.targets = [self.anchor_target]

    def mtp(self):
        window = self.times[-MEDIAN_TIME_SPAN:]
        return statistics.median_low(window) if len(window) < MEDIAN_TIME_SPAN else sorted(window)[len(window) // 2]

    def next_target(self):
        """Target for the block about to be appended, using the current tip as pindexPrev."""
        tip_height = self.heights[-1]
        tip_time = self.times[-1]
        time_diff = tip_time - self.anchor_prev_time
        height_diff = tip_height - self.anchor_height
        return calculate_asert(self.anchor_target, IBT, time_diff, height_diff, POW_LIMIT, self.half_life)

    def append_block(self, desired_time):
        """
        Append a block whose *desired* arrival time is `desired_time` (absolute,
        seconds since anchor-parent epoch), clamped to the real consensus
        timestamp constraints relative to what's already on the simulated chain:
          - nTime must exceed MTP of the previous MEDIAN_TIME_SPAN blocks.
          - nTime must not exceed "now" (== desired_time's own honest clock) +
            MAX_FUTURE_BLOCK_TIME -- not a binding constraint for an honestly
            time-stamped simulated miner, included for completeness/documentation.
        Returns the actual recorded time (post-clamp) and the target that was
        used to produce this block.
        """
        target = self.next_target()
        floor = self.mtp() + 1
        # Real nTime is a uint32 whole-second field; round rather than carry
        # float sub-second precision into the fixed-point integer math below.
        rounded_desired = int(round(desired_time))
        actual_time = max(rounded_desired, floor)
        mtp_clamped = actual_time != rounded_desired  # did the MTP floor itself bind, not just int rounding
        self.heights.append(self.heights[-1] + 1)
        self.times.append(actual_time)
        self.targets.append(target)
        return actual_time, target, mtp_clamped


def rel_difficulty(target):
    """Difficulty relative to powLimit (== relative_target inverse)."""
    return POW_LIMIT / target


# ---------------------------------------------------------------------------
# Deterministic (expected-value) scenario driver
# ---------------------------------------------------------------------------

def run_deterministic(half_life, hashrate_schedule, max_blocks):
    """
    hashrate_schedule(height) -> multiplier k relative to anchor hashrate.
    Advances height-by-height; each block's *expected* arrival time is
    IBT / (rel_target * k), added deterministically (no randomness). Applies
    the real MTP floor to the resulting timestamp.
    Returns a list of dicts, one per block: height, time, target, rel_diff, k,
    instantaneous rate ratio actual/target.
    """
    sim = ChainSim(half_life)
    t = sim.times[-1]
    log = []
    for h in range(1, max_blocks + 1):
        k = hashrate_schedule(h)
        target = sim.next_target()
        rel_target = target / POW_LIMIT
        expected_dt = IBT / (rel_target * k)
        desired_time = t + expected_dt
        actual_time, used_target, mtp_clamped = sim.append_block(desired_time)
        actual_dt = actual_time - t
        t = actual_time
        rate_ratio = IBT / actual_dt if actual_dt > 0 else float("inf")
        log.append({
            "h": h, "time": actual_time, "target": used_target,
            "rel_diff": rel_difficulty(used_target), "k": k,
            "rate_ratio": rate_ratio, "mtp_clamped": mtp_clamped,
        })
    return log


def run_stochastic(half_life, hashrate_schedule, max_blocks, rng):
    """
    Same as run_deterministic but block arrival is a Poisson process: given
    the current target and hashrate multiplier k, the true instantaneous
    block rate is (rel_target * k) / IBT blocks/sec, so inter-block time is
    drawn from Exponential(rate). Applies the same real MTP floor.
    """
    sim = ChainSim(half_life)
    t = sim.times[-1]
    log = []
    for h in range(1, max_blocks + 1):
        k = hashrate_schedule(h)
        target = sim.next_target()
        rel_target = target / POW_LIMIT
        rate = (rel_target * k) / IBT  # blocks per second
        dt = rng.expovariate(rate) if rate > 0 else float("inf")
        desired_time = t + dt
        actual_time, used_target, mtp_clamped = sim.append_block(desired_time)
        actual_dt = actual_time - t
        t = actual_time
        rate_ratio = IBT / actual_dt if actual_dt > 0 else float("inf")
        log.append({
            "h": h, "time": actual_time, "target": used_target,
            "rel_diff": rel_difficulty(used_target), "k": k,
            "rate_ratio": rate_ratio, "mtp_clamped": mtp_clamped,
        })
    return log


# ---------------------------------------------------------------------------
# Scenario definitions
# ---------------------------------------------------------------------------

def surge_then_revert(surge_k, surge_blocks):
    """1x baseline -> surge_k for surge_blocks blocks -> back to 1x, forever after."""
    def schedule(h):
        return surge_k if h <= surge_blocks else 1.0
    return schedule, surge_blocks + 3000  # enough tail to observe recovery


def pool_hopping(on_k, on_blocks, off_blocks, cycles):
    """
    Alternates on_k (miner present) for on_blocks with 1x (miner absent) for
    off_blocks, repeated `cycles` times -- models a large pool switching a
    BitAIcoin-directed hashrate allocation on and off.
    """
    period = on_blocks + off_blocks

    def schedule(h):
        pos = (h - 1) % period
        return on_k if pos < on_blocks else 1.0

    return schedule, period * cycles + 500


def measure_recovery_windowed(log, shock_end_height, window=20, tolerance=0.15):
    """
    Rolling-window recovery metric, used for the STOCHASTIC report instead of
    measure_recovery()'s per-block-consecutive check.

    Real reason this is needed, not just an alternative: under a genuine
    Poisson arrival process, the coefficient of variation of a SINGLE
    inter-block interval is 1.0 (stdev == mean, for Exponential(rate)) --
    so individual blocks routinely land 2x, 3x, even 5x+ off the mean rate
    purely from honest statistical noise, with zero relation to whether the
    DAA has "settled." A metric that demands 20 CONSECUTIVE individual
    blocks each within 10% of target is essentially unsatisfiable under
    stochastic arrivals regardless of half-life -- confirmed empirically
    below (report_stochastic() shows "None" for every seed under the
    strict per-block metric). That is a genuine, disclosed finding about
    the metric, not a simulation bug: per-block deviation is simply the
    wrong yardstick once arrivals are stochastic. A rolling average over a
    real window of blocks is the metric that is actually meaningful, since
    it is what the DAA's own halflife-scale response operates on.
    """
    for h in range(shock_end_height + window, len(log) - window):
        span_time = log[h - 1]["time"] - log[h - 1 - window]["time"]
        if span_time <= 0:
            continue
        rolling_ratio = (window * IBT) / span_time
        if abs(rolling_ratio - 1.0) <= tolerance:
            # persistence check: the NEXT window must also be within tolerance
            span_time2 = log[min(h - 1 + window, len(log) - 1)]["time"] - log[h - 1]["time"]
            if span_time2 > 0:
                rolling_ratio2 = (window * IBT) / span_time2
                if abs(rolling_ratio2 - 1.0) <= tolerance:
                    return h - shock_end_height
    return None


def measure_recovery(log, shock_end_height, tolerance=0.10, needed_consecutive=20):
    """
    After the shock ends at shock_end_height, find the first run of
    `needed_consecutive` consecutive blocks whose rate_ratio is within
    `tolerance` of 1.0. Returns (blocks_after_shock_to_settle, worst rate
    ratio observed during/after the transition back).
    """
    consecutive = 0
    settle_at = None
    worst = 1.0
    for entry in log:
        if entry["h"] < shock_end_height:
            continue
        ratio = entry["rate_ratio"]
        instant_mult = ratio if ratio >= 1 else 1.0 / ratio
        if entry["h"] >= shock_end_height:
            worst = max(worst, instant_mult) if entry["h"] < shock_end_height + needed_consecutive * 5 else worst
        deviation = abs(ratio - 1.0)
        if deviation <= tolerance:
            consecutive += 1
            if consecutive == needed_consecutive and settle_at is None:
                settle_at = entry["h"] - needed_consecutive + 1 - shock_end_height
        else:
            consecutive = 0
    return settle_at, worst


# ---------------------------------------------------------------------------
# Report generation
# ---------------------------------------------------------------------------

def report_surge_scenarios():
    print("=" * 100)
    print("SURGE-THEN-REVERT: 1x -> Kx for N blocks -> back to 1x. Recovery measured in")
    print("blocks/hours AFTER the surge ends (not from t=0).")
    print("=" * 100)
    header = f"{'half-life':<10}{'surge':<8}{'held (blk)':<12}{'recover (blk)':<16}{'recover (h)':<13}{'worst instant mult during transition':<40}"
    print(header)
    print("-" * len(header))
    for hl_name, hl in HALF_LIVES.items():
        for surge_k in (10, 100, 1000):
            for held in (20, 100, 500):
                schedule, max_blocks = surge_then_revert(surge_k, held)
                log = run_deterministic(hl, schedule, max_blocks)
                settle_blocks, worst = measure_recovery(log, shock_end_height=held)
                if settle_blocks is not None:
                    # wall-clock hours for those recovery blocks, post-shock
                    t_shock_end = log[held - 1]["time"]
                    t_settle = log[held - 1 + settle_blocks + 19]["time"] if held - 1 + settle_blocks + 19 < len(log) else None
                    hrs = f"{(t_settle - t_shock_end) / 3600.0:.1f}" if t_settle is not None else "n/a"
                else:
                    hrs = "n/a"
                sb = str(settle_blocks) if settle_blocks is not None else "n/a(>tail)"
                print(f"{hl_name:<10}{str(surge_k)+'x':<8}{held:<12}{sb:<16}{hrs:<13}{f'{worst:.1f}x':<10}")
        print()


def report_pool_hopping():
    print("=" * 100)
    print("POOL-HOPPING: alternating on_k for `on` blocks / 1x for `off` blocks, repeated.")
    print("Reports worst instantaneous rate ratio seen across all cycles, and whether")
    print("difficulty ever fully re-settles to 1x during the `off` phases.")
    print("=" * 100)
    header = f"{'half-life':<10}{'on_k':<8}{'on/off (blk)':<14}{'cycles':<8}{'worst instant mult':<20}{'ever resettles off-phase':<26}"
    print(header)
    print("-" * len(header))
    for hl_name, hl in HALF_LIVES.items():
        for on_k, on_blocks, off_blocks, cycles in [(10, 50, 50, 6), (100, 20, 100, 4), (1000, 10, 200, 3)]:
            schedule, max_blocks = pool_hopping(on_k, on_blocks, off_blocks, cycles)
            log = run_deterministic(hl, schedule, max_blocks)
            worst = max(e["rate_ratio"] if e["rate_ratio"] >= 1 else 1.0 / e["rate_ratio"] for e in log)
            # check whether, at the END of any off-phase, rate_ratio was within 10% of 1.0
            period = on_blocks + off_blocks
            resettled_any_off_phase = False
            for cyc in range(cycles):
                off_end_h = cyc * period + on_blocks + off_blocks
                if off_end_h <= len(log):
                    e = log[off_end_h - 1]
                    if abs(e["rate_ratio"] - 1.0) <= 0.10:
                        resettled_any_off_phase = True
            print(f"{hl_name:<10}{str(on_k)+'x':<8}{f'{on_blocks}/{off_blocks}':<14}{cycles:<8}{f'{worst:.1f}x':<20}{'yes' if resettled_any_off_phase else 'no':<26}")
        print()


def report_stochastic():
    print("=" * 100)
    print("STOCHASTIC (Poisson-arrival) vs DETERMINISTIC: 100x surge held 100 blocks then")
    print("revert to 1x. 5 random seeds per half-life.")
    print()
    print("First pass used the deterministic report's strict per-block metric (20")
    print("CONSECUTIVE individual blocks each within 10% of target) on the stochastic")
    print("logs too, and it returned None for every single seed at every half-life --")
    print("investigated rather than dismissed: a Poisson arrival process has per-block")
    print("coefficient of variation = 1.0 (stdev == mean for Exponential), so individual")
    print("blocks routinely land 2-5x off the mean by honest chance alone, making 20-in-a-row")
    print("within 10% essentially unsatisfiable regardless of half-life. That's a real")
    print("property of the metric, not of the DAA -- so a rolling-window metric (below)")
    print("is used instead, since it's what a halflife-scale DAA response actually operates on.")
    print("=" * 100)
    header = f"{'half-life':<10}{'seed':<6}{'strict recover':<16}{'windowed recover':<18}{'worst instant mult':<20}"
    print(header)
    print("-" * len(header))
    for hl_name, hl in HALF_LIVES.items():
        schedule, max_blocks = surge_then_revert(100, 100)
        det_log = run_deterministic(hl, schedule, max_blocks)
        det_settle, det_worst = measure_recovery(det_log, shock_end_height=100)
        det_settle_w = measure_recovery_windowed(det_log, shock_end_height=100)
        print(f"{hl_name:<10}{'(det)':<6}{str(det_settle):<16}{str(det_settle_w):<18}{f'{det_worst:.1f}x':<20}")
        settles_strict, settles_windowed = [], []
        for seed in range(5):
            rng = random.Random(seed)
            log = run_stochastic(hl, schedule, max_blocks, rng)
            settle, worst = measure_recovery(log, shock_end_height=100)
            settle_w = measure_recovery_windowed(log, shock_end_height=100)
            settles_strict.append(settle)
            settles_windowed.append(settle_w)
            print(f"{'':<10}{seed:<6}{str(settle):<16}{str(settle_w):<18}{f'{worst:.1f}x':<20}")
        valid_w = [s for s in settles_windowed if s is not None]
        if valid_w:
            print(f"{'':<10}{'spread(w)':<6}min={min(valid_w)} max={max(valid_w)} mean={sum(valid_w)/len(valid_w):.0f}")
        print()


def report_mtp_impact():
    print("=" * 100)
    print("MTP-FLOOR IMPACT: how often the real MTP-floor constraint (nTime >")
    print("median of previous 11 blocks) actually binds during the sharpest, most")
    print("sustained bursts (short 20-block surges above showed 0/3020 -- not sustained")
    print("or extreme enough for the DAA to have eased the target far before the surge")
    print("ends; these scenarios hold the surge much longer to actually probe the floor).")
    print("=" * 100)
    header = f"{'half-life':<10}{'scenario':<28}{'blocks MTP-clamped':<20}{'of total':<10}"
    print(header)
    print("-" * len(header))
    for hl_name, hl in HALF_LIVES.items():
        for surge_k, held in [(1000, 500), (1000, 2000), (10000, 500)]:
            schedule, max_blocks = surge_then_revert(surge_k, held)
            log = run_deterministic(hl, schedule, max_blocks)
            clamped_during_surge = sum(1 for e in log if e["mtp_clamped"] and e["h"] <= held)
            print(f"{hl_name:<10}{f'{surge_k}x/{held}blk surge':<28}{clamped_during_surge:<20}{clamped_during_surge}/{held}")
    print()


if __name__ == "__main__":
    report_surge_scenarios()
    report_pool_hopping()
    report_stochastic()
    report_mtp_impact()
    print("No half-life is selected by this script. Comparison only, per explicit instruction.")
